version: "3"
services:
  node:
    image: USER/Your-Pre-Built-Image
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
