version: "3"
services:
  node:
    image:  sivakumarsagar/nginx:latest
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
